### ISSUE TITLE
Code replication is throwing an error.

### ISSUE THREAD

**Issue by Carmen279252** [Luffy03/CISC-R#6]
Hello, I encountered an issue while trying to replicate your code.

The error occurred in line 147 of the file dataset/make_query_txt.py. It seems that the dimension of vec at this point is batch_size * 256, （default：batch_size=8）while the dimension of vecs_all is [4, 256]. When I attempt to execute vecs_all[index, :] += vec, it leads to a dimension mismatch error. 

Could you please assist me in resolving this issue? Thank you!

**Comment by Luffy03** [comment]
Hi, many thanks for your attention to our work first!
It looks weird to me since we have not met this problem. But it seems that we can use 'view' or 'unsqueeze' to ensure 'vecs_all' and 'vec' have the same size. Would you please try it and find out what is going on?
Feel free to contact me again if you have further problems.
